
LAYOUT_R11_R12 = [
    ('Tipo', 1, 3, 'X'),
    ('CNPJ do Declarante', 4, 17, 'CNPJ'),
    (None, 18, 31, 'SPACE'),
    ('CNPJ do Estabelecimento Detentor do Crédito', 32, 45, 'CNPJ'),
    ('ANO', 46, 49, 'XN'),
    ('MES', 50, 51, 'XN'),
    ('Decêndio/Quinzena do Período de Apuração', 52, 52, 'X'),
    ('CFOP', 53, 56, 'cfop'),
    ('Operações com Crédito do Imposto - Base de Cálculo', 57, 70, 'R+'),
    ('Operações com Crédito do Imposto - IPI Creditado', 71, 84, 'R+'),
    ('Operações sem Crédito do Imposto - Isentas ou Não Tributadas', 85, 98, 'R+'),
    ('Operações sem Crédito do Imposto - Outras', 99, 112, 'R+'),
]

LAYOUT_R13 = [
    ('Tipo', 1, 3, 'X'),
    ('CNPJ do Declarante', 4, 17, 'CNPJ'),
    (None, 18, 31, 'SPACE'),
    ('CNPJ do Estabelecimento Detentor do Crédito', 32, 45, 'CNPJ'),
    ('CNPJ do Emitente', 46, 59, 'CNPJ'),
    ('Nº da Nota Fiscal', 60, 68, 'XN'),
    ('Série/Subsérie', 69, 71, 'X'),
    ('Data de Emissão', 72, 79, 'DATA'),
    ('Data de Entrada no Estabelecimento Detentor do Crédito', 80, 87, 'DATA'),
    ('CFOP', 88, 91, 'cfop'),
    ('Valor Total', 92, 105, 'R+'),
    ('Valor do IPI Destacado', 106, 119, 'R+'),
    ('Valor do IPI Creditado no Livro RAIPI', 120, 133, 'R+'),
]

LAYOUT_R15 = [
    ('Tipo', 1, 3, 'X'),
    ('CNPJ do Declarante', 4, 17, 'CNPJ'),
    (None, 18, 31, 'SPACE'),
    ('CNPJ do Estabelecimento Detentor do Crédito', 32, 45, 'CNPJ'),
    ('CNPJ do Emitente', 46, 59, 'CNPJ'),
    ('Nº da Nota Fiscal', 60, 68, 'XN'),
    ('Série/Subsérie', 69, 71, 'X'),
    ('Data de Emissão', 72, 79, 'DATA'),
    ('Data de Entrada no Estabelecimento Detentor do Crédito', 80, 87, 'DATA'),
    ('CFOP', 88, 91, 'cfop'),
    ('Valor Total', 92, 105, 'R+'),
    ('Valor do IPI Destacado', 106, 119, 'R+'),
    ('Valor do IPI Creditado no Livro RAIPI', 120, 133, 'R+'),
    ('Espécie do Crédito', 134, 134, 'CRED'),
    ('Decêndio/Quinzena do Período de Escrituração', 135, 135, 'DECENDIO1'),
    ('Mês do Período de Escrituração', 136, 137, 'MM'),
    ('Ano do Período de Escrituração', 138, 141, 'AAAA'),
]

LAYOUT_R21 = [
    ('Tipo', 1, 3, 'X'),
    ('CNPJ do Declarante', 4, 17, 'CNPJ'),
    (None, 18, 31, 'SPACE'),
    ('CNPJ do Estabelecimento Detentor do Crédito', 32, 45, 'CNPJ'),
    ('Ano do Período de Apuração', 46, 49, 'AAAA'),
    ('Mês do Período de Apuração', 50, 51, 'MM'),
    ('Decêndio/Quinzena do Período de Apuração', 52, 52, 'DECENDIO2'),
    ('Existe Movimento no Período?', 53, 53, 'N'),
    ('Demonstrativo de Créditos - Por Entradas do Mercado Nacional', 54, 67, 'R+'),
    ('Demonstrativo de Créditos - Por Entradas do Mercado Externo', 68, 81, 'R+'),
    ('Demonstrativo de Créditos - Estorno de Débitos', 82, 95, 'R+'),
    ('Demonstrativo de Créditos - Crédito Presumido', 96, 109, 'R+'),
    ('Demonstrativo de Créditos - Créditos Extemporâneos', 110, 123, 'R+'),
    ('Demonstrativo de Créditos - Demais Créditos', 124, 137, 'R+'),
    ('Demonstrativo de Débitos - Por Saídas para o Mercado Nacional', 138, 151, 'R+'),
    ('Demonstrativo de Débitos - Estorno de Créditos', 152, 165, 'R+'),
    ('Demonstrativo de Débitos - Ressarcimentos de Créditos', 166, 179, 'R+'),
    ('Demonstrativo de Débitos - Outros Débitos', 180, 193, 'R+'),
]
